In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from Island import Island, Member
from time import time
from Land import Land
import os

rng = np.random.default_rng()
island = Island(5, (5, 5), 2022)

In [2]:
island.land.owner

[[None, None, None, None, None],
 [None,
  None,
  None,
  Marvell(0) ,
  Boy(3) ],
 [None, None, None, None, None],
 [None, None, Morgen(1) , None, None],
 [None,
  None,
  Arnisha(4) ,
  Jerin(2) ,
  None]]

In [36]:
rng.choice(range(10), 3, replace=False)

array([1, 5, 7])

In [3]:
m1 = Member("1", id=1, surviver_id=0, rng=rng)
m2 = Member("2", id=2, surviver_id=0, rng=rng)
m3 = Member("3", id=3, surviver_id=0, rng=rng)
m4 = Member("4", id=4, surviver_id=0, rng=rng)
m5 = Member("5", id=5, surviver_id=0, rng=rng)
m6 = Member("6", id=6, surviver_id=0, rng=rng)
m7 = Member("7", id=7, surviver_id=0, rng=rng)
m8 = Member("8", id=8, surviver_id=0, rng=rng)

In [6]:
land = Land((6, 5))
land.owner = [
    [None, m1, m1, None, m1],
    [m1, m1, m3, m5, m5],
    [m6, m6, m4, m4, m1],
    [m7, m1, None, m1, m1],
    [m1, m1, m1, m1, m1],
    [m4, m8, m2, m1, m1],
]

In [8]:
clear_list = []
self_blocked_list = []
neighbor_blocked_list = []
empty_loc_list = []

is_passed = np.zeros((6, 5))

land._find_neighbors(
    clear_list,
    self_blocked_list,
    neighbor_blocked_list,
    empty_loc_list,
    location = (2, 2),
    member = m4,
    is_passed = is_passed,
    iteration_cnt = 0,
    island = None
)

print(is_passed)
print(clear_list)
print(self_blocked_list)
print(neighbor_blocked_list)

land._find_neighbors(
    clear_list,
    self_blocked_list,
    neighbor_blocked_list,
    empty_loc_list,
    location = (5, 0),
    member = m4,
    is_passed = is_passed,
    iteration_cnt = 0,
    island = None
)

print(is_passed)
print(clear_list)
print(self_blocked_list)
print(neighbor_blocked_list)
print(empty_loc_list)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1.]
 [1. 1. 1. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[5(5) , 6(6) , 7(7) ]
[1(1) , 3(3) ]
[]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1.]
 [1. 1. 1. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]]
[5(5) , 6(6) , 7(7) , 8(8) ]
[1(1) , 3(3) ]
[2(2) ]
[(0, 3), (3, 2), (0, 0)]


In [9]:
1 == True

True

In [1]:
os.mkdir("test1/0/")

In [6]:
island = Island(50, random_seed=2022)

In [7]:
island.fight()
island.trade()

In [8]:
island.save_current_island("test_")

In [4]:
x.save_to_row()

attack
offer
reproduce


name  surviver_id  productivity   vitality      cargo  age  \
0  Marvell            0     14.493567  26.657547  37.384384   89   

   attack_self_productivity  attack_self_vitality  attack_self_cargo  \
0                  0.054261              0.695186           0.868202   

   attack_self_age  ...  reproduce_obj_productivity  reproduce_obj_vitality  \
0              0.0  ...                    0.270527                0.620712   

   reproduce_obj_cargo  reproduce_obj_age  reproduce_victim_overlap  \
0             0.270702                0.0                  0.738614   

   reproduce_benefit_overlap  reproduce_victim_passive  \
0                   0.408641                 -0.314751   

   reproduce_victim_active  reproduce_benefit_passive  \
0                -0.615778                   0.949761   

   reproduce_benefit_active  
0                  0.262216  

[1 rows x 48 columns]

In [ ]:
island.new_round()

In [ ]:
island.produce()

In [ ]:
island.fight()

In [ ]:
island.consume()

In [ ]:
island.relationship_dict["benefit"][26, 18]

In [ ]:
island.trade()

In [ ]:
island.trade()
island.print_info()

In [ ]:
island.relationship_dict["benefit"][1, 48]

In [ ]:
island.new_round()

In [ ]:
for mem in groups[0]:
    for obj in groups[0]:
        if mem is not obj:
            print(mem, obj, mem.decision("fight", obj, island))


In [ ]:
member1 = island.all_members[0]
member2 = island.all_members[1]

In [ ]:
member1.fight_parameter

In [ ]:
member1.fight_parameter[0] = 0
member1.parameter_dict["fight"]

In [ ]:
inputs = list(member1._generate_decision_inputs(member2, island).values())
member1._decision(member1.fight_parameter, inputs)

In [ ]:
range(1, 10)

In [ ]:
Member.born(island.all_members[0], island.all_members[1])

In [ ]:
a = [1, 2, 3, 4]
np.repeat(a, 2)

In [ ]:
a = ["a", "b"]
b = [np.random.rand(2), np.random.rand(2)]
d = dict(zip(a, b))
d

In [ ]:
n = {key: d[key] for key in d.keys()}
n

In [ ]:
class foo:
    def __init__(self, a):
        self.a = a

    @property
    def return_a(self):
        return self.a * 2

In [ ]:
x = foo(1)
x.return_a

In [ ]:
island = Island(42, random_seed=2022)
island.fight()

In [ ]:
# seed = time()
rng = np.random.default_rng(2022)

In [ ]:
rng.random(1)

In [ ]:
def f(x: np.ndarray):
    print(x)

In [ ]:
(np.array([None, 1]) == None).any()

In [ ]:
b = np.array([[0], [1]])
c = np.array([[10], [100]])
a = [b, c]
a

In [ ]:
for idx in range(len(a)):
    a[idx].resize(1, refcheck=False)

a

In [ ]:
b

In [ ]:
island = Island(4)
print(island.victim_memory)
np.fill_diagonal(island.victim_memory, np.nan)
print(island.victim_memory)


In [ ]:
somebody_die = [island.current_members[3], island.current_members[2]]

In [ ]:
somebody_born = [Member("aha", 1, None), Member("aha", 99, None)]

In [ ]:
print(island.all_members)
print(island.current_members)
print(island.victim_memory)
print(island.benefit_memory)

In [ ]:
island.member_list_modify(somebody_born, somebody_die, np.zeros((2, 4)), np.zeros((4, 2)))
print(island.all_members)
print(island.current_members)
print(island.current_member_num)
print(island.victim_memory)
print(island.benefit_memory)
print(island.current_members[-1].surviver_id)
print(island.all_members[-1].surviver_id)
print(island.all_members[-1].id)

In [ ]:
a = np.random.rand(5, 5)
a

In [ ]:
a = np.delete(a, (1, 2), axis=0)
a = np.delete(a, (1, 2), axis=1)
a

In [ ]:
a = np.delete(a, (1), axis=1)
a

In [ ]:
b = a[0]
b

In [ ]:
np.sort(b)[::-1]

In [ ]:
island = Island(10)
print(island.all_members)


In [ ]:
island.all_members
print(island.current_members)

In [ ]:
island.all_members[0].name = "aaaaa"
print(island.all_members)
print(island.current_members)

In [ ]:
np.random.seed(1)
x = np.random.random(10)
print(x)
print(np.random.normal(x[0], 1, 10))

In [ ]:
a = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
a.append([[9, 0], [1, 2]])
arr = np.array(a)
arr.reshape(3, 4)

In [ ]:
arr.reshape(3, 2, 2)

In [ ]:
pd.DataFrame([[1,2,3],[4,5,6]], index=['a','b'], columns=["g", 'h', 'j'])

In [ ]:
a = ["a", "b", "c"]
np.random.shuffle(a)
a

In [ ]:
a = np.array([0, 1, 2, 3])
b = [True, False, True, False]
a[b]

In [ ]:
plt.plot([1 ,2 ,3], [1, 2, None])

In [ ]:
print(plt.cm.RdYlGn)

In [ ]:
list = np.array([1, 2, 3 ,4, 5])
list[list < 3] = 0
list

In [ ]:
list = ['iarry', 'harry', 'hbrry']
arg_sort_list = np.argsort(list)
arg_sort_list

In [ ]:
list = [list[i] for i in arg_sort_list]
list

In [ ]:
np.split((np.arange(10)), 2)

In [ ]:
mat = np.random.rand(3, 3)
mat = [[1, 2, 3], [2, 0, 4], [1, 2, 1]]
mat

In [ ]:
max_mat_element = np.argmax(np.sum(mat, 1))
max_mat_element

In [ ]:
class test_class:
    def __init__(self):
        self.att = 1

def change(cl):
    cl.att = 2

a = test_class()
change(a)
a.att

In [ ]:
str = ""
str == ""

In [ ]:
np.random.choice([1, 2, 3], size=1, p = [1, 2, 3])