In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from Island import Island, Member
from time import time

In [2]:
island = Island(50, random_seed=2022)

In [3]:
island.new_round()

################ 0 ################
=============== 攻击 ===============
=============== 给予 ===============
本轮出生：[]
本轮死亡：[]
本轮总给予：0
本轮总攻击：0
本轮总产量：0
	 id   Name       Age    Vit     Cargo
	[0] Marvell:    170,   26.66,   37.38
	[1] Morgen:     804,   32.08,   70.90
	[2] Jerin:      106,   43.96,   50.06
	[3] Boy:        62,   45.68,   66.50
	[4] Arnisha:    635,   87.89,   20.52
	[5] Karoline:   407,   23.32,   0.84
	[6] Aime:       476,   44.56,   26.65
	[7] Lamesha:    595,   27.91,   51.06
	[8] Maya:       488,   55.66,   24.40
	[9] Latoiya:    806,   56.42,   26.95
	[10] Lashayla:   936,   55.78,   87.93
	[11] Gabriella:  722,   41.22,   48.05
	[12] Kristinejoy: 70,   59.93,   92.65
	[13] Waymon:     526,   69.14,   61.92
	[14] Elisabeth:  59,   63.19,   7.09
	[15] Corwyn:     825,   21.25,   86.77
	[16] Scotty:     361,   75.07,   32.12
	[17] Karriem:    503,   62.53,   28.28
	[18] Sareena:    651,   68.03,   35.32
	[19] Arleen:     383,   68.07,   92.08
	[20] Tristin:    258,   73.2

In [4]:
island.produce()

In [5]:
island.fight()

Korinne(28) 死了


In [6]:
island.consume()

Nidya(21) 死了
Jermaine(24) 死了
Reem(33) 死了
Taiwan(35) 死了


In [7]:
island.trade()

In [8]:
island.reproduce(group_size=30)

0 0.0
20.962717364081062 2.8080842458728315
0 0.0
0.9469318567669127 0.10050637750885726
0 0.0
0 0.0


In [18]:
island.new_round()

################ 10 ################
=============== 攻击 ===============
	Waymon(13) --22.0-> Scotty(16)
	Scotty(16) --24.9-> Waymon(13)
	Taiwan(35) --6.4-> Sareena(18)
	Sareena(18) --22.7-> Taiwan(35)
	Lamesha(7) --8.2-> Lashayla(10)
	Lashayla(10) --16.5-> Lamesha(7)
	Arnisha(4) --28.8-> Morgen(1)
	Morgen(1) --8.6-> Arnisha(4)
	Jermaine(24) --6.5-> Tristin(20)
	Tristin(20) --26.8-> Jermaine(24)
	Nicolette(43) --16.6-> Jerin(2)
	Jerin(2) --12.8-> Nicolette(43)
	Darbie(41) --17.5-> Tremell(44)
	Tremell(44) --24.4-> Darbie(41)
	Maya(8) --19.0-> Boy(3)
	Boy(3) --16.1-> Maya(8)
	Tomeshia(42) --8.5-> Karriem(17)
	Karriem(17) --18.1-> Tomeshia(42)
	Mirtha(46) --7.8-> Chenoa(37)
	Chenoa(37) --22.3-> Mirtha(46)
	Ellena(39) --31.1-> Korinne(28)
	Korinne(28) --3.7-> Ellena(39)
	Aime(6) --15.0-> Casia(25)
	Casia(25) --13.7-> Aime(6)
=============== 给予 ===============
	Scotty(16) --0.0-> Silas(50)
	Ellena(39) --2.8-> Silas(50)
	Renada(31) --0.0-> Kjersten(51)
	Aireal(32) --0.1-> Kjersten(51)
	Tomes

In [ ]:
for mem in groups[0]:
    for obj in groups[0]:
        if mem is not obj:
            print(mem, obj, mem.decision("fight", obj, island))


Donetta(0) Christyn(1) 1.9814009745630035
Donetta(0) Pearson(2) 2.0915540244016757
Donetta(0) Jenea(3) 2.846092493963173
Donetta(0) Chella(4) 2.1365431036118894
Christyn(1) Donetta(0) 0.7194964569588894
Christyn(1) Pearson(2) 1.1504669353591621
Christyn(1) Jenea(3) 1.393790093511261
Christyn(1) Chella(4) 0.5412719136836731
Pearson(2) Donetta(0) -0.6311395622625386
Pearson(2) Christyn(1) 0.41698158506555283
Pearson(2) Jenea(3) -1.0594480094763146
Pearson(2) Chella(4) 0.5477678479215317
Jenea(3) Donetta(0) -1.9929301805289028
Jenea(3) Christyn(1) -2.013082768364038
Jenea(3) Pearson(2) -1.5650373818244554
Jenea(3) Chella(4) -1.869348387635385
Chella(4) Donetta(0) 1.3648085956262477
Chella(4) Christyn(1) 1.3332823751821103
Chella(4) Pearson(2) 1.0871949020329128
Chella(4) Jenea(3) 1.7703707448054953


In [ ]:
member1 = island.all_members[0]
member2 = island.all_members[1]

In [ ]:
member1.fight_parameter

array([ 0.60121465, -0.89372271,  0.20997226,  0.59343662,  0.15537462,
        0.0519948 , -0.81174596, -0.97773462,  0.85431746, -0.07127653,
        0.1856762 ,  0.19105307,  0.61329238, -0.50925015])

In [ ]:
member1.fight_parameter[0] = 0
member1.parameter_dict["fight"]

array([ 0.        , -0.89372271,  0.20997226,  0.59343662,  0.15537462,
        0.0519948 , -0.81174596, -0.97773462,  0.85431746, -0.07127653,
        0.1856762 ,  0.19105307,  0.61329238, -0.50925015])

In [ ]:
inputs = list(member1._generate_decision_inputs(member2, island).values())
member1._decision(member1.fight_parameter, inputs)

308.04875809195704

In [ ]:
range(1, 10)

range(1, 10)

In [ ]:
Member.born(island.all_members[0], island.all_members[1])

In [ ]:
a = [1, 2, 3, 4]
np.repeat(a, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [ ]:
a = ["a", "b"]
b = [np.random.rand(2), np.random.rand(2)]
d = dict(zip(a, b))
d

NameError: name 'np' is not defined

In [ ]:
n = {key: d[key] for key in d.keys()}
n

{'a': 'c', 'b': 'd'}

In [ ]:
class foo:
    def __init__(self, a):
        self.a = a

    @property
    def return_a(self):
        return self.a * 2

In [ ]:
x = foo(1)
x.return_a

2

In [ ]:
island = Island(42, random_seed=2022)
island.fight()

[Marvell(0), Morgen(1), Jerin(2), Boy(3), Arnisha(4), Karoline(5), Aime(6), Lamesha(7), Maya(8), Latoiya(9), Lashayla(10)]
[Gabriella(11), Kristinejoy(12), Waymon(13), Elisabeth(14), Corwyn(15), Scotty(16), Karriem(17), Sareena(18), Arleen(19), Tristin(20), Nidya(21)]
[Jemar(22), Aziz(23), Jermaine(24), Casia(25), Anastassia(26), Alicen(27), Korinne(28), Deontrae(29), Willie(30), Renada(31)]
[Aireal(32), Reem(33), Taralyn(34), Taiwan(35), Arik(36), Chenoa(37), Janelle(38), Ellena(39), Valarie(40), Darbie(41)]


In [ ]:
# seed = time()
rng = np.random.default_rng(2022)

In [ ]:
rng.random(1)

array([0.09299006])

In [ ]:
def f(x: np.ndarray):
    print(x)

In [ ]:
(np.array([None, 1]) == None).any()

In [ ]:
b = np.array([[0], [1]])
c = np.array([[10], [100]])
a = [b, c]
a

In [ ]:
for idx in range(len(a)):
    a[idx].resize(1, refcheck=False)

a

In [ ]:
b

In [ ]:
island = Island(4)
print(island.victim_memory)
np.fill_diagonal(island.victim_memory, np.nan)
print(island.victim_memory)


In [ ]:
somebody_die = [island.current_members[3], island.current_members[2]]

In [ ]:
somebody_born = [Member("aha", 1, None), Member("aha", 99, None)]

In [ ]:
print(island.all_members)
print(island.current_members)
print(island.victim_memory)
print(island.benefit_memory)

In [ ]:
island.member_list_modify(somebody_born, somebody_die, np.zeros((2, 4)), np.zeros((4, 2)))
print(island.all_members)
print(island.current_members)
print(island.current_member_num)
print(island.victim_memory)
print(island.benefit_memory)
print(island.current_members[-1].surviver_id)
print(island.all_members[-1].surviver_id)
print(island.all_members[-1].id)

In [ ]:
a = np.random.rand(5, 5)
a

In [ ]:
a = np.delete(a, (1, 2), axis=0)
a = np.delete(a, (1, 2), axis=1)
a

In [ ]:
a = np.delete(a, (1), axis=1)
a

In [ ]:
b = a[0]
b

In [ ]:
np.sort(b)[::-1]

In [ ]:
island = Island(10)
print(island.all_members)


In [ ]:
island.all_members
print(island.current_members)

In [ ]:
island.all_members[0].name = "aaaaa"
print(island.all_members)
print(island.current_members)

In [ ]:
np.random.seed(1)
x = np.random.random(10)
print(x)
print(np.random.normal(x[0], 1, 10))

In [ ]:
a = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
a.append([[9, 0], [1, 2]])
arr = np.array(a)
arr.reshape(3, 4)

In [ ]:
arr.reshape(3, 2, 2)

In [ ]:
pd.DataFrame([[1,2,3],[4,5,6]], index=['a','b'], columns=["g", 'h', 'j'])

In [ ]:
a = ["a", "b", "c"]
np.random.shuffle(a)
a

In [ ]:
a = np.array([0, 1, 2, 3])
b = [True, False, True, False]
a[b]

In [ ]:
plt.plot([1 ,2 ,3], [1, 2, None])

In [ ]:
print(plt.cm.RdYlGn)

In [ ]:
list = np.array([1, 2, 3 ,4, 5])
list[list < 3] = 0
list

In [ ]:
list = ['iarry', 'harry', 'hbrry']
arg_sort_list = np.argsort(list)
arg_sort_list

In [ ]:
list = [list[i] for i in arg_sort_list]
list

In [ ]:
np.split((np.arange(10)), 2)

In [ ]:
mat = np.random.rand(3, 3)
mat = [[1, 2, 3], [2, 0, 4], [1, 2, 1]]
mat

In [ ]:
max_mat_element = np.argmax(np.sum(mat, 1))
max_mat_element

In [ ]:
class test_class:
    def __init__(self):
        self.att = 1

def change(cl):
    cl.att = 2

a = test_class()
change(a)
a.att

In [ ]:
str = ""
str == ""

In [ ]:
np.random.choice([1, 2, 3], size=1, p = [1, 2, 3])