In [11]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from Island import Island, Member
from time import time

In [12]:
island = Island(50, random_seed=2022)

In [13]:
island.print_info()

========================== Vitality ==========================
	[0] Marvell:    Age: 170,  Vit: 26.7, Cargo: 37.4
	[1] Morgen:     Age: 804,  Vit: 32.1, Cargo: 70.9
	[2] Jerin:      Age: 106,  Vit: 44.0, Cargo: 50.1
	[3] Boy:        Age: 62,  Vit: 45.7, Cargo: 66.5
	[4] Arnisha:    Age: 635,  Vit: 87.9, Cargo: 20.5
	[5] Karoline:   Age: 407,  Vit: 23.3, Cargo: 0.8
	[6] Aime:       Age: 476,  Vit: 44.6, Cargo: 26.6
	[7] Lamesha:    Age: 595,  Vit: 27.9, Cargo: 51.1
	[8] Maya:       Age: 488,  Vit: 55.7, Cargo: 24.4
	[9] Latoiya:    Age: 806,  Vit: 56.4, Cargo: 26.9
	[10] Lashayla:   Age: 936,  Vit: 55.8, Cargo: 87.9
	[11] Gabriella:  Age: 722,  Vit: 41.2, Cargo: 48.1
	[12] Kristinejoy: Age: 70,  Vit: 59.9, Cargo: 92.7
	[13] Waymon:     Age: 526,  Vit: 69.1, Cargo: 61.9
	[14] Elisabeth:  Age: 59,  Vit: 63.2, Cargo: 7.1
	[15] Corwyn:     Age: 825,  Vit: 21.3, Cargo: 86.8
	[16] Scotty:     Age: 361,  Vit: 75.1, Cargo: 32.1
	[17] Karriem:    Age: 503,  Vit: 62.5, Cargo: 28.3
	[18] Sareena: 

In [14]:
island.produce()
island.produce()
island.produce()
island.produce()
island.print_info()


========================== Vitality ==========================
	[0] Marvell:    Age: 170,  Vit: 26.7, Cargo: 87.3
	[1] Morgen:     Age: 804,  Vit: 32.1, Cargo: 146.4
	[2] Jerin:      Age: 106,  Vit: 44.0, Cargo: 99.3
	[3] Boy:        Age: 62,  Vit: 45.7, Cargo: 123.4
	[4] Arnisha:    Age: 635,  Vit: 87.9, Cargo: 100.3
	[5] Karoline:   Age: 407,  Vit: 23.3, Cargo: 53.0
	[6] Aime:       Age: 476,  Vit: 44.6, Cargo: 73.3
	[7] Lamesha:    Age: 595,  Vit: 27.9, Cargo: 126.3
	[8] Maya:       Age: 488,  Vit: 55.7, Cargo: 74.2
	[9] Latoiya:    Age: 806,  Vit: 56.4, Cargo: 76.9
	[10] Lashayla:   Age: 936,  Vit: 55.8, Cargo: 162.4
	[11] Gabriella:  Age: 722,  Vit: 41.2, Cargo: 122.5
	[12] Kristinejoy: Age: 70,  Vit: 59.9, Cargo: 151.0
	[13] Waymon:     Age: 526,  Vit: 69.1, Cargo: 119.0
	[14] Elisabeth:  Age: 59,  Vit: 63.2, Cargo: 75.8
	[15] Corwyn:     Age: 825,  Vit: 21.3, Cargo: 150.8
	[16] Scotty:     Age: 361,  Vit: 75.1, Cargo: 101.1
	[17] Karriem:    Age: 503,  Vit: 62.5, Cargo: 95.2
	[1

In [15]:
island.fight()
island.fight()
island.print_info()

Waymon(13) Scotty(16)
Taiwan(35) Lamesha(7)
Sareena(18) Lashayla(10)
Arnisha(4) Morgen(1)
Jermaine(24) Tristin(20)
Nicolette(43) Jerin(2)
Maya(8) Boy(3)
Reem(33) Taralyn(34)
Tomeshia(42) Karriem(17)
Mirtha(46) Chenoa(37)
Ellena(39) Korinne(28)
Korinne(28) 死了
Renada(31) Janelle(38)
Aime(6) Casia(25)
Aime(6) Casia(25)
Lamesha(7) Lashayla(10)
Tristin(20) Willie(30)
Aireal(32) Ellena(39)
Renada(31) Nicolette(43)
Waymon(13) Arnisha(4)
Huston(48) Gabriella(11)
Sareena(18) Morgen(1)
Tremell(44) Latoiya(9)
Arik(36) Jermaine(24)
Marvell(0) Rashad(49)
Tomeshia(42) Reem(33)
Mirtha(46) Karoline(5)
========================== Vitality ==========================
	[0] Marvell:    Age: 170,  Vit: 14.3, Cargo: 75.4
	[1] Morgen:     Age: 804,  Vit: 8.6, Cargo: 119.7
	[2] Jerin:      Age: 106,  Vit: 35.8, Cargo: 90.8
	[3] Boy:        Age: 62,  Vit: 38.6, Cargo: 114.0
	[4] Arnisha:    Age: 635,  Vit: 76.7, Cargo: 87.0
	[5] Karoline:   Age: 407,  Vit: 20.4, Cargo: 50.9
	[6] Aime:       Age: 476,  Vit: 31.7,

In [16]:
island.consume()
island.print_info()

Morgen(1) 死了
Nidya(21) 死了
Jermaine(24) 死了
Reem(33) 死了
Arik(36) 死了
========================== Vitality ==========================
	[0] Marvell:    Age: 170,  Vit: 79.7, Cargo: 0.0
	[2] Jerin:      Age: 106,  Vit: 100.0, Cargo: 16.7
	[3] Boy:        Age: 62,  Vit: 100.0, Cargo: 42.6
	[4] Arnisha:    Age: 635,  Vit: 100.0, Cargo: 53.7
	[5] Karoline:   Age: 407,  Vit: 61.4, Cargo: 0.0
	[6] Aime:       Age: 476,  Vit: 80.1, Cargo: 0.0
	[7] Lamesha:    Age: 595,  Vit: 100.0, Cargo: 24.8
	[8] Maya:       Age: 488,  Vit: 100.0, Cargo: 5.5
	[9] Latoiya:    Age: 806,  Vit: 100.0, Cargo: 1.7
	[10] Lashayla:   Age: 936,  Vit: 100.0, Cargo: 57.8
	[11] Gabriella:  Age: 722,  Vit: 100.0, Cargo: 45.8
	[12] Kristinejoy: Age: 70,  Vit: 100.0, Cargo: 101.0
	[13] Waymon:     Age: 526,  Vit: 100.0, Cargo: 28.5
	[14] Elisabeth:  Age: 59,  Vit: 100.0, Cargo: 29.0
	[15] Corwyn:     Age: 825,  Vit: 100.0, Cargo: 60.3
	[16] Scotty:     Age: 361,  Vit: 100.0, Cargo: 44.2
	[17] Karriem:    Age: 503,  Vit: 100.0, 

In [17]:
island.relationship_dict["benefit"][26, 18]

66.30383339425701

In [18]:
island.all_members[30].surviver_id
# island.all_members[19].surviver_id

26

In [19]:
island.trade()
island.print_info()

Arleen(19) Willie(30)
========================== Vitality ==========================
	[0] Marvell:    Age: 170,  Vit: 79.7, Cargo: 0.0
	[2] Jerin:      Age: 106,  Vit: 100.0, Cargo: 16.7
	[3] Boy:        Age: 62,  Vit: 100.0, Cargo: 42.6
	[4] Arnisha:    Age: 635,  Vit: 100.0, Cargo: 53.7
	[5] Karoline:   Age: 407,  Vit: 61.4, Cargo: 0.0
	[6] Aime:       Age: 476,  Vit: 80.1, Cargo: 0.0
	[7] Lamesha:    Age: 595,  Vit: 100.0, Cargo: 24.8
	[8] Maya:       Age: 488,  Vit: 100.0, Cargo: 5.5
	[9] Latoiya:    Age: 806,  Vit: 100.0, Cargo: 1.7
	[10] Lashayla:   Age: 936,  Vit: 100.0, Cargo: 57.8
	[11] Gabriella:  Age: 722,  Vit: 100.0, Cargo: 45.8
	[12] Kristinejoy: Age: 70,  Vit: 100.0, Cargo: 101.0
	[13] Waymon:     Age: 526,  Vit: 100.0, Cargo: 28.5
	[14] Elisabeth:  Age: 59,  Vit: 100.0, Cargo: 29.0
	[15] Corwyn:     Age: 825,  Vit: 100.0, Cargo: 60.3
	[16] Scotty:     Age: 361,  Vit: 100.0, Cargo: 44.2
	[17] Karriem:    Age: 503,  Vit: 100.0, Cargo: 39.2
	[18] Sareena:    Age: 651,  Vit

In [20]:
island.relationship_dict["benefit"][1, 48]

IndexError: index 48 is out of bounds for axis 1 with size 44

In [ ]:
island.reproduce(group_size=20)
island.print_info()

Tomeshia(42) Renada(31)
========================== Vitality ==========================
	Marvell:    Age: 170,  Vit: 66.5, Cargo: 0.0
	Morgen:     Age: 804,  Vit: 73.6, Cargo: 0.0
	Jerin:      Age: 106,  Vit: 79.7, Cargo: 0.0
	Boy:        Age: 62,  Vit: 93.5, Cargo: 0.0
	Arnisha:    Age: 635,  Vit: 100.0, Cargo: 9.7
	Karoline:   Age: 407,  Vit: 22.5, Cargo: 0.0
	Aime:       Age: 476,  Vit: 48.1, Cargo: 4.6
	Maya:       Age: 488,  Vit: 47.3, Cargo: 0.0
	Latoiya:    Age: 806,  Vit: 84.7, Cargo: 0.0
	Lashayla:   Age: 936,  Vit: 100.0, Cargo: 19.5
	Gabriella:  Age: 722,  Vit: 97.7, Cargo: 0.0
	Kristinejoy: Age: 70,  Vit: 100.0, Cargo: 54.4
	Waymon:     Age: 526,  Vit: 100.0, Cargo: 10.5
	Elisabeth:  Age: 59,  Vit: 60.4, Cargo: 0.0
	Corwyn:     Age: 825,  Vit: 100.0, Cargo: 12.3
	Scotty:     Age: 361,  Vit: 92.4, Cargo: 0.0
	Karriem:    Age: 503,  Vit: 89.0, Cargo: 2.7
	Sareena:    Age: 651,  Vit: 89.7, Cargo: 3.0
	Arleen:     Age: 383,  Vit: 100.0, Cargo: 56.6
	Tristin:    Age: 258,  Vit: 1

In [ ]:
for mem in groups[0]:
    for obj in groups[0]:
        if mem is not obj:
            print(mem, obj, mem.decision("fight", obj, island))


Donetta(0) Christyn(1) 1.9814009745630035
Donetta(0) Pearson(2) 2.0915540244016757
Donetta(0) Jenea(3) 2.846092493963173
Donetta(0) Chella(4) 2.1365431036118894
Christyn(1) Donetta(0) 0.7194964569588894
Christyn(1) Pearson(2) 1.1504669353591621
Christyn(1) Jenea(3) 1.393790093511261
Christyn(1) Chella(4) 0.5412719136836731
Pearson(2) Donetta(0) -0.6311395622625386
Pearson(2) Christyn(1) 0.41698158506555283
Pearson(2) Jenea(3) -1.0594480094763146
Pearson(2) Chella(4) 0.5477678479215317
Jenea(3) Donetta(0) -1.9929301805289028
Jenea(3) Christyn(1) -2.013082768364038
Jenea(3) Pearson(2) -1.5650373818244554
Jenea(3) Chella(4) -1.869348387635385
Chella(4) Donetta(0) 1.3648085956262477
Chella(4) Christyn(1) 1.3332823751821103
Chella(4) Pearson(2) 1.0871949020329128
Chella(4) Jenea(3) 1.7703707448054953


In [ ]:
member1 = island.all_members[0]
member2 = island.all_members[1]

In [ ]:
member1.fight_parameter

array([ 0.60121465, -0.89372271,  0.20997226,  0.59343662,  0.15537462,
        0.0519948 , -0.81174596, -0.97773462,  0.85431746, -0.07127653,
        0.1856762 ,  0.19105307,  0.61329238, -0.50925015])

In [ ]:
member1.fight_parameter[0] = 0
member1.parameter_dict["fight"]

array([ 0.        , -0.89372271,  0.20997226,  0.59343662,  0.15537462,
        0.0519948 , -0.81174596, -0.97773462,  0.85431746, -0.07127653,
        0.1856762 ,  0.19105307,  0.61329238, -0.50925015])

In [ ]:
inputs = list(member1._generate_decision_inputs(member2, island).values())
member1._decision(member1.fight_parameter, inputs)

308.04875809195704

In [ ]:
range(1, 10)

range(1, 10)

In [ ]:
Member.born(island.all_members[0], island.all_members[1])

In [ ]:
a = [1, 2, 3, 4]
np.repeat(a, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [ ]:
a = ["a", "b"]
b = [np.random.rand(2), np.random.rand(2)]
d = dict(zip(a, b))
d

NameError: name 'np' is not defined

In [ ]:
n = {key: d[key] for key in d.keys()}
n

{'a': 'c', 'b': 'd'}

In [ ]:
class foo:
    def __init__(self, a):
        self.a = a

    @property
    def return_a(self):
        return self.a * 2

In [ ]:
x = foo(1)
x.return_a

2

In [ ]:
island = Island(42, random_seed=2022)
island.fight()

[Marvell(0), Morgen(1), Jerin(2), Boy(3), Arnisha(4), Karoline(5), Aime(6), Lamesha(7), Maya(8), Latoiya(9), Lashayla(10)]
[Gabriella(11), Kristinejoy(12), Waymon(13), Elisabeth(14), Corwyn(15), Scotty(16), Karriem(17), Sareena(18), Arleen(19), Tristin(20), Nidya(21)]
[Jemar(22), Aziz(23), Jermaine(24), Casia(25), Anastassia(26), Alicen(27), Korinne(28), Deontrae(29), Willie(30), Renada(31)]
[Aireal(32), Reem(33), Taralyn(34), Taiwan(35), Arik(36), Chenoa(37), Janelle(38), Ellena(39), Valarie(40), Darbie(41)]


In [ ]:
# seed = time()
rng = np.random.default_rng(2022)

In [ ]:
rng.random(1)

array([0.09299006])

In [ ]:
def f(x: np.ndarray):
    print(x)

In [ ]:
(np.array([None, 1]) == None).any()

In [ ]:
b = np.array([[0], [1]])
c = np.array([[10], [100]])
a = [b, c]
a

In [ ]:
for idx in range(len(a)):
    a[idx].resize(1, refcheck=False)

a

In [ ]:
b

In [ ]:
island = Island(4)
print(island.victim_memory)
np.fill_diagonal(island.victim_memory, np.nan)
print(island.victim_memory)


In [ ]:
somebody_die = [island.current_members[3], island.current_members[2]]

In [ ]:
somebody_born = [Member("aha", 1, None), Member("aha", 99, None)]

In [ ]:
print(island.all_members)
print(island.current_members)
print(island.victim_memory)
print(island.benefit_memory)

In [ ]:
island.member_list_modify(somebody_born, somebody_die, np.zeros((2, 4)), np.zeros((4, 2)))
print(island.all_members)
print(island.current_members)
print(island.current_member_num)
print(island.victim_memory)
print(island.benefit_memory)
print(island.current_members[-1].surviver_id)
print(island.all_members[-1].surviver_id)
print(island.all_members[-1].id)

In [ ]:
a = np.random.rand(5, 5)
a

In [ ]:
a = np.delete(a, (1, 2), axis=0)
a = np.delete(a, (1, 2), axis=1)
a

In [ ]:
a = np.delete(a, (1), axis=1)
a

In [ ]:
b = a[0]
b

In [ ]:
np.sort(b)[::-1]

In [ ]:
island = Island(10)
print(island.all_members)


In [ ]:
island.all_members
print(island.current_members)

In [ ]:
island.all_members[0].name = "aaaaa"
print(island.all_members)
print(island.current_members)

In [ ]:
np.random.seed(1)
x = np.random.random(10)
print(x)
print(np.random.normal(x[0], 1, 10))

In [ ]:
a = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
a.append([[9, 0], [1, 2]])
arr = np.array(a)
arr.reshape(3, 4)

In [ ]:
arr.reshape(3, 2, 2)

In [ ]:
pd.DataFrame([[1,2,3],[4,5,6]], index=['a','b'], columns=["g", 'h', 'j'])

In [ ]:
a = ["a", "b", "c"]
np.random.shuffle(a)
a

In [ ]:
a = np.array([0, 1, 2, 3])
b = [True, False, True, False]
a[b]

In [ ]:
plt.plot([1 ,2 ,3], [1, 2, None])

In [ ]:
print(plt.cm.RdYlGn)

In [ ]:
list = np.array([1, 2, 3 ,4, 5])
list[list < 3] = 0
list

In [ ]:
list = ['iarry', 'harry', 'hbrry']
arg_sort_list = np.argsort(list)
arg_sort_list

In [ ]:
list = [list[i] for i in arg_sort_list]
list

In [ ]:
np.split((np.arange(10)), 2)

In [ ]:
mat = np.random.rand(3, 3)
mat = [[1, 2, 3], [2, 0, 4], [1, 2, 1]]
mat

In [ ]:
max_mat_element = np.argmax(np.sum(mat, 1))
max_mat_element

In [ ]:
class test_class:
    def __init__(self):
        self.att = 1

def change(cl):
    cl.att = 2

a = test_class()
change(a)
a.att

In [ ]:
str = ""
str == ""

In [ ]:
np.random.choice([1, 2, 3], size=1, p = [1, 2, 3])