In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from Island import Island, Member
from time import time

In [2]:
island = Island(6, random_seed=2022)

In [3]:
morgen = island.all_members[1]
jerin = island.all_members[2]
print(morgen.parameter_dict, "\n", jerin.parameter_dict)


{'attack': array([ 0.69335449,  0.30021242,  0.88662627,  0.1596948 , -0.92706574,
        0.66497366, -0.92155438,  0.93361718, -0.38442777,  0.0152856 ,
       -0.02627679, -0.86484199, -0.20145745,  0.05222746]), 'offer': array([ 0.77592916,  0.8960261 , -0.6164001 ,  0.89954539, -0.18196087,
        0.31509757, -0.24479855, -0.63143469,  0.85121596,  0.73633811,
        0.38017479, -0.61453754,  0.78038426, -0.54111655]), 'reproduce': array([ 0.35461665, -0.38019079, -0.52606298,  0.93650382,  0.69870272,
       -0.08568537, -0.17138518, -0.94961342, -0.95153072,  0.94659099,
       -0.29641733,  0.69680569, -0.89344182,  0.95101649])} 
 {'attack': array([-0.9306096 ,  0.74787361,  0.81918124, -0.06379883, -0.83323245,
       -0.80859394,  0.99777689, -0.10039634,  0.38615183, -0.79229325,
       -0.67344884,  0.15651497, -0.11811114, -0.71582395]), 'offer': array([ 0.27274302, -0.03011145, -0.9547157 ,  0.11528618, -0.18416492,
        0.77243824, -0.78471731,  0.53414985,  0.6966

In [4]:
# island.fight()
print()
island.trade()


Morgen(1) Jerin(2)


In [5]:
morgen = island.all_members[1]
jerin = island.all_members[2]
print(morgen.parameter_dict, "\n", jerin.parameter_dict)


{'attack': array([ 0.69335449,  0.30021242,  0.88662627,  0.1596948 , -0.92706574,
        0.66497366, -0.92155438,  0.93361718, -0.38442777,  0.0152856 ,
       -0.02627679, -0.86484199, -0.20145745,  0.05222746]), 'offer': array([ 0.77592916,  0.8960261 , -0.6164001 ,  0.89954539, -0.18196087,
        0.31509757, -0.24479855, -0.63143469,  0.85121596,  0.73633811,
        0.38017479, -0.61453754,  0.78038426, -0.54111655]), 'reproduce': array([ 0.35461665, -0.38019079, -0.52606298,  0.93650382,  0.69870272,
       -0.08568537, -0.17138518, -0.94961342, -0.95153072,  0.94659099,
       -0.29641733,  0.69680569, -0.89344182,  0.95101649])} 
 {'attack': array([-1.18627552e-01,  5.24043012e-01,  8.52903757e-01,  4.79479864e-02,
       -8.80149097e-01, -7.18101401e-02,  3.81112546e-02,  4.16610420e-01,
        8.62033430e-04, -3.88503826e-01, -3.49862816e-01, -3.54163508e-01,
       -1.59784296e-01, -3.31798246e-01]), 'offer': array([ 0.52433609,  0.43295732, -0.7855579 ,  0.50741578, -0.

In [16]:
for mem in groups[0]:
    for obj in groups[0]:
        if mem is not obj:
            print(mem, obj, mem.decision("fight", obj, island))


Donetta(0) Christyn(1) 1.9814009745630035
Donetta(0) Pearson(2) 2.0915540244016757
Donetta(0) Jenea(3) 2.846092493963173
Donetta(0) Chella(4) 2.1365431036118894
Christyn(1) Donetta(0) 0.7194964569588894
Christyn(1) Pearson(2) 1.1504669353591621
Christyn(1) Jenea(3) 1.393790093511261
Christyn(1) Chella(4) 0.5412719136836731
Pearson(2) Donetta(0) -0.6311395622625386
Pearson(2) Christyn(1) 0.41698158506555283
Pearson(2) Jenea(3) -1.0594480094763146
Pearson(2) Chella(4) 0.5477678479215317
Jenea(3) Donetta(0) -1.9929301805289028
Jenea(3) Christyn(1) -2.013082768364038
Jenea(3) Pearson(2) -1.5650373818244554
Jenea(3) Chella(4) -1.869348387635385
Chella(4) Donetta(0) 1.3648085956262477
Chella(4) Christyn(1) 1.3332823751821103
Chella(4) Pearson(2) 1.0871949020329128
Chella(4) Jenea(3) 1.7703707448054953


In [4]:
member1 = island.all_members[0]
member2 = island.all_members[1]

In [4]:
member1.fight_parameter

array([ 0.60121465, -0.89372271,  0.20997226,  0.59343662,  0.15537462,
        0.0519948 , -0.81174596, -0.97773462,  0.85431746, -0.07127653,
        0.1856762 ,  0.19105307,  0.61329238, -0.50925015])

In [5]:
member1.fight_parameter[0] = 0
member1.parameter_dict["fight"]

array([ 0.        , -0.89372271,  0.20997226,  0.59343662,  0.15537462,
        0.0519948 , -0.81174596, -0.97773462,  0.85431746, -0.07127653,
        0.1856762 ,  0.19105307,  0.61329238, -0.50925015])

In [5]:
inputs = list(member1._generate_decision_inputs(member2, island).values())
member1._decision(member1.fight_parameter, inputs)

308.04875809195704

In [8]:
range(1, 10)

range(1, 10)

In [ ]:
Member.born(island.all_members[0], island.all_members[1])

In [9]:
a = [1, 2, 3, 4]
np.repeat(a, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [5]:
a = ["a", "b"]
b = [np.random.rand(2), np.random.rand(2)]
d = dict(zip(a, b))
d

NameError: name 'np' is not defined

In [4]:
n = {key: d[key] for key in d.keys()}
n

{'a': 'c', 'b': 'd'}

In [16]:
class foo:
    def __init__(self, a):
        self.a = a

    @property
    def return_a(self):
        return self.a * 2

In [17]:
x = foo(1)
x.return_a

2

In [2]:
island = Island(42, random_seed=2022)
island.fight()

[Marvell(0), Morgen(1), Jerin(2), Boy(3), Arnisha(4), Karoline(5), Aime(6), Lamesha(7), Maya(8), Latoiya(9), Lashayla(10)]
[Gabriella(11), Kristinejoy(12), Waymon(13), Elisabeth(14), Corwyn(15), Scotty(16), Karriem(17), Sareena(18), Arleen(19), Tristin(20), Nidya(21)]
[Jemar(22), Aziz(23), Jermaine(24), Casia(25), Anastassia(26), Alicen(27), Korinne(28), Deontrae(29), Willie(30), Renada(31)]
[Aireal(32), Reem(33), Taralyn(34), Taiwan(35), Arik(36), Chenoa(37), Janelle(38), Ellena(39), Valarie(40), Darbie(41)]


In [4]:
# seed = time()
rng = np.random.default_rng(2022)

In [6]:
rng.random(1)

array([0.09299006])

In [ ]:
def f(x: np.ndarray):
    print(x)

In [ ]:
(np.array([None, 1]) == None).any()

In [ ]:
b = np.array([[0], [1]])
c = np.array([[10], [100]])
a = [b, c]
a

In [ ]:
for idx in range(len(a)):
    a[idx].resize(1, refcheck=False)

a

In [ ]:
b

In [ ]:
island = Island(4)
print(island.victim_memory)
np.fill_diagonal(island.victim_memory, np.nan)
print(island.victim_memory)


In [ ]:
somebody_die = [island.current_members[3], island.current_members[2]]

In [ ]:
somebody_born = [Member("aha", 1, None), Member("aha", 99, None)]

In [ ]:
print(island.all_members)
print(island.current_members)
print(island.victim_memory)
print(island.benefit_memory)

In [ ]:
island.member_list_modify(somebody_born, somebody_die, np.zeros((2, 4)), np.zeros((4, 2)))
print(island.all_members)
print(island.current_members)
print(island.current_member_num)
print(island.victim_memory)
print(island.benefit_memory)
print(island.current_members[-1].surviver_id)
print(island.all_members[-1].surviver_id)
print(island.all_members[-1].id)

In [ ]:
a = np.random.rand(5, 5)
a

In [ ]:
a = np.delete(a, (1, 2), axis=0)
a = np.delete(a, (1, 2), axis=1)
a

In [ ]:
a = np.delete(a, (1), axis=1)
a

In [ ]:
b = a[0]
b

In [ ]:
np.sort(b)[::-1]

In [ ]:
island = Island(10)
print(island.all_members)


In [ ]:
island.all_members
print(island.current_members)

In [ ]:
island.all_members[0].name = "aaaaa"
print(island.all_members)
print(island.current_members)

In [ ]:
np.random.seed(1)
x = np.random.random(10)
print(x)
print(np.random.normal(x[0], 1, 10))

In [ ]:
a = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
a.append([[9, 0], [1, 2]])
arr = np.array(a)
arr.reshape(3, 4)

In [ ]:
arr.reshape(3, 2, 2)

In [ ]:
pd.DataFrame([[1,2,3],[4,5,6]], index=['a','b'], columns=["g", 'h', 'j'])

In [ ]:
a = ["a", "b", "c"]
np.random.shuffle(a)
a

In [ ]:
a = np.array([0, 1, 2, 3])
b = [True, False, True, False]
a[b]

In [ ]:
plt.plot([1 ,2 ,3], [1, 2, None])

In [ ]:
print(plt.cm.RdYlGn)

In [ ]:
list = np.array([1, 2, 3 ,4, 5])
list[list < 3] = 0
list

In [ ]:
list = ['iarry', 'harry', 'hbrry']
arg_sort_list = np.argsort(list)
arg_sort_list

In [ ]:
list = [list[i] for i in arg_sort_list]
list

In [ ]:
np.split((np.arange(10)), 2)

In [ ]:
mat = np.random.rand(3, 3)
mat = [[1, 2, 3], [2, 0, 4], [1, 2, 1]]
mat

In [ ]:
max_mat_element = np.argmax(np.sum(mat, 1))
max_mat_element

In [ ]:
class test_class:
    def __init__(self):
        self.att = 1

def change(cl):
    cl.att = 2

a = test_class()
change(a)
a.att

In [ ]:
str = ""
str == ""

In [ ]:
np.random.choice([1, 2, 3], size=1, p = [1, 2, 3])