In [1]:
import numpy as np
import matplotlib.pyplot as plt

def fitness(strategy, population):
    A = np.array([[3, 1], [1, 2]]) # Payoff matrix
    f = np.sum(population * np.dot(population, A), axis=1) # Fitness of each strategy
    return f

def update(population, fitness):
    f_total = np.sum(fitness) # Total fitness
    proportions = fitness / f_total # Proportion of each strategy
    new_population = proportions * np.sum(population) # New population size
    return new_population

def replicator_dynamics(population, generations):
    for i in range(generations):
        f = fitness(population)
        population = update(population, f)
    return population

if __name__ == '__main__':
    population = np.array([0.9, 0.1]) # Initial population
    generations = 100
    final_population = replicator_dynamics(population, generations)
    print(final_population)
    plt.plot(final_population)
    plt.xlabel('Generation')
    plt.ylabel('Population Proportion')
    plt.show()


TypeError: fitness() missing 1 required positional argument: 'population'

In [25]:
import numpy as np
import scipy

def fitness(strategy, population):
    # Calculate the average fitness of each strategy in the population
    avg_fitness = np.mean(strategy, axis=0)
    # Calculate the relative fitness of each strategy
    rel_fitness = strategy - avg_fitness
    # Update the population based on the relative fitness of each strategy
    population = population @ np.exp(rel_fitness)
    # Normalize the population so it sums to 1
    population = population / np.sum(population)
    return population

def replicator_dynamics(strategy, population, steps):
    # Repeat the fitness calculation for a specified number of steps
    for i in range(steps):
        population = fitness(strategy, population)
    return population

# Define the strategy matrix
strategy = np.array([[4, 0], [3, 2]])

# Define the initial population
population = np.array([0.5, 0.5])

# Run the replicator dynamics model for 100 steps
final_population = replicator_dynamics(strategy, population, 1000)

print("Final population:", final_population)

Final population: [0.32699936 0.67300064]


In [ ]:
# Calculate the average fitness of each strategy in the population
avg_fitness = np.mean(strategy, axis=0)
# Calculate the relative fitness of each strategy
rel_fitness = strategy - avg_fitness

scipy.linalg.eig(np.exp(rel_fitness).transpose())

(array([1.46997502+0.j, 2.89702808+0.j]),
 array([[-0.95921344, -0.43702651],
        [ 0.28268283, -0.89944863]]))

In [9]:
import numpy as np
import scipy.integrate as spi

def replicator_dynamics(y, t, params):
    N = len(y)
    γ = params
    ff = np.zeros(N)
    for i in range(N):
        for j in range(N):
            ff[i] += y[j] * (y[i] * (1 - y[i]) + γ * y[i] * (y[j]-y[i]))
    return ff

y0 = [0.2, 0.3, 0.5] # initial populations of strategies
t = [0, 5, 10, 20] # time points to evaluate
γ = 0.1 # parameter for the replicator dynamics equations
params = [γ]

# solve the ODE
sol = spi.odeint(replicator_dynamics, y0, t, args=(params, ))

TypeError: can't multiply sequence by non-int of type 'numpy.float64'

In [ ]:
# Calculate the average fitness of each strategy in the population
avg_fitness = np.mean(strategy, axis=0)
# Calculate the relative fitness of each strategy
rel_fitness = strategy - avg_fitness

scipy.linalg.eig(np.exp(rel_fitness).transpose())

(array([1.46997502+0.j, 2.89702808+0.j]),
 array([[-0.95921344, -0.43702651],
        [ 0.28268283, -0.89944863]]))

In [ ]:
# Calculate the average fitness of each strategy in the population
avg_fitness = np.mean(strategy, axis=0)
# Calculate the relative fitness of each strategy
rel_fitness = strategy - avg_fitness

scipy.linalg.eig(np.exp(rel_fitness).transpose())

(array([1.46997502+0.j, 2.89702808+0.j]),
 array([[-0.95921344, -0.43702651],
        [ 0.28268283, -0.89944863]]))

In [ ]:
# Calculate the average fitness of each strategy in the population
avg_fitness = np.mean(strategy, axis=0)
# Calculate the relative fitness of each strategy
rel_fitness = strategy - avg_fitness

scipy.linalg.eig(np.exp(rel_fitness).transpose())

(array([1.46997502+0.j, 2.89702808+0.j]),
 array([[-0.95921344, -0.43702651],
        [ 0.28268283, -0.89944863]]))

In [ ]:
# Calculate the average fitness of each strategy in the population
avg_fitness = np.mean(strategy, axis=0)
# Calculate the relative fitness of each strategy
rel_fitness = strategy - avg_fitness

scipy.linalg.eig(np.exp(rel_fitness).transpose())

(array([1.46997502+0.j, 2.89702808+0.j]),
 array([[-0.95921344, -0.43702651],
        [ 0.28268283, -0.89944863]]))

In [8]:
# Calculate the average fitness of each strategy in the population
avg_fitness = np.mean(strategy, axis=0)
# Calculate the relative fitness of each strategy
rel_fitness = strategy - avg_fitness

scipy.linalg.eig(np.exp(rel_fitness).transpose())

(array([1.46997502+0.j, 2.89702808+0.j]),
 array([[-0.95921344, -0.43702651],
        [ 0.28268283, -0.89944863]]))

In [ ]:
def generate_payoff_matrix(transition_matrix, payoff_A, payoff_B, rounds):
    n = len(transition_matrix)
    payoff_matrix = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            expected_payoff_A = payoff_A * transition_matrix[i, j]
            expected_payoff_B = payoff_B * transition_matrix[j, i]
            for k in range(1, rounds):
                expected_payoff_A = expected_payoff_A * transition_matrix[j, i] + payoff_A * transition_matrix[i, j]
                expected_payoff_B = expected_payoff_B * transition_matrix[i, j] + payoff_B * transition_matrix[j, i]
            payoff_matrix[i, j] = (expected_payoff_A + expected_payoff_B) / 2
    return payoff_matrix


In [18]:
# Define the transition matrix for each round
transition_matrix = np.array([[0.8, 0.2], [0.3, 0.7]])

# Define the rewards for each state
payoff_A = 10
payoff_B = 20

# Calculate the expected payoffs for each combination of strategies for the next 5 rounds
payoff_matrix = np.array([[payoff_A, payoff_B], [payoff_A, payoff_B]])
for i in range(100):
    payoff_matrix = np.dot(payoff_matrix, transition_matrix)

print("Payoff matrix 5 rounds ahead:")
print(payoff_matrix)


Payoff matrix 5 rounds ahead:
[[18. 12.]
 [18. 12.]]


In [19]:
# Define the transition matrix for each round
transition_matrix = np.array([[0.8, 0.2], [0.3, 0.7]])

# Define the rewards for each state
payoff_A = 10
payoff_B = 20

# Create an array to store the expected payoffs for each combination of strategies
payoff = np.zeros((6, 2, 2))

# Calculate the expected payoffs for each combination of strategies for the first round
payoff[0, 0, 0] = payoff_A * transition_matrix[0, 0]
payoff[0, 0, 1] = payoff_A * transition_matrix[0, 1]
payoff[0, 1, 0] = payoff_B * transition_matrix[1, 0]
payoff[0, 1, 1] = payoff_B * transition_matrix[1, 1]

# Calculate the expected payoffs for each combination of strategies for the next 5 rounds
for i in range(1, 6):
    payoff[i, 0, 0] = payoff[i-1, 0, 0] * transition_matrix[0, 0] + payoff[i-1, 1, 0] * transition_matrix[0, 1]
    payoff[i, 0, 1] = payoff[i-1, 0, 1] * transition_matrix[0, 0] + payoff[i-1, 1, 1] * transition_matrix[0, 1]
    payoff[i, 1, 0] = payoff[i-1, 0, 0] * transition_matrix[1, 0] + payoff[i-1, 1, 0] * transition_matrix[1, 1]
    payoff[i, 1, 1] = payoff[i-1, 0, 1] * transition_matrix[1, 0] + payoff[i-1, 1, 1] * transition_matrix[1, 1]

print("Payoff matrix 5 rounds ahead:")
print(payoff[5, :, :])


Payoff matrix 5 rounds ahead:
[[7.225  6.65  ]
 [7.1625 7.025 ]]
